
# Symbols solver_minimal_1 exports to the filter side modules it hosts.
#
# Keep this list tight: with MAIN_MODULE=2 an entry does not merely add a
# symbol-table slot, it also pins the function against dead-stripping, so a
# dead export drags its whole call graph into the binary. Trimming 86 unused
# entries once cut ~76KB (-1%) off solver_minimal_1.wasm.
#
# To re-derive the list after adding or rebuilding a filter, disassemble each
# *_1.wasm paired with solver_minimal (wasm-dis), collect its "env"/GOT.mem/
# GOT.func imports, subtract what the filter exports itself, what this binary
# already exports (llvm-nm) and what the JS glue defines (solver_minimal_1.js:
# both the wasmImports object *and* the standalone "function invoke_*"
# trampolines - forgetting the latter inflates the result badly). What is left
# is genuinely missing; cross-check each one against solver_1's symbol table
# before adding it, since GPAC_DISABLE_ISOM and friends mean many gf_isom_*/
# gf_sc_*/gf_scene_* symbols simply do not exist in this build.
#
# Prefer, in order: reconfigure the third-party library so it stops needing
# the symbol (libraw's --disable-openmp, libheif's
# -D__EMSCRIPTEN_STANDALONE_WASM__); else link the dependency into the filter
# (poppler carries its own libjpeg.a); export from here only as a last resort.
# The one exception is the C++ runtime - a filter must NOT bundle its own
# libc++/libc++abi, two copies break libc++'s static state across the module
# boundary (see filters/libheif/CMakeLists.txt).

SET(GPAC
    '_fout_register'
    '_fin_register'
    '_writegen_register'
    '_main'
)

# GPAC core API functions actually imported (from "env") by the filters this
# minimal build is meant to be used with (image/audio decode+transcode via
# writegen - see test-player/*.js's "solver_minimal_1" usages). Generated by
# disassembling each filter's *_1.wasm (wasm-dis) and collecting its "env"
# gf_* imports; symbols only needed by filters that require full gpac (isom/
# scenegraph/compositor, e.g. isobmff, theora, libmpeg2's mp4 muxing path -
# those explicitly use "solver_1", never "solver_minimal_1") are excluded on
# purpose, since gpac_minimal doesn't build ISOBMFF/scenegraph/compositor
# support at all. If a new filter needs to be paired with solver_minimal and
# fails to dlopen with an "undefined symbol" error, re-run the same
# wasm-dis scan against that filter's wasm and add whatever's missing here
# (as long as it's actually defined in libgpac_static.a - GPAC_DISABLE_ISOM
# and friends mean plenty of gf_isom_*/gf_sc_*/gf_scene_*/gf_bifs_* symbols
# simply don't exist in this build).
SET(FILTERS
    '_gf_4cc_to_str'
    '_gf_audio_fmt_bit_depth'
    '_gf_audio_fmt_get_layout_from_cicp'
    '_gf_base64_decode'
    '_gf_bs_align'
    '_gf_bs_available'
    '_gf_bs_bits_available'
    '_gf_bs_del'
    '_gf_bs_enable_emulation_byte_removal'
    '_gf_bs_get_bit_offset'
    '_gf_bs_get_bit_position'
    '_gf_bs_get_content'
    '_gf_bs_get_emulation_byte_removed'
    '_gf_bs_get_position'
    '_gf_bs_get_size'
    '_gf_bs_is_align'
    '_gf_bs_is_overflow'
    '_gf_bs_log_idx'
    '_gf_bs_mark_overflow'
    '_gf_bs_new'
    '_gf_bs_peek_bits'
    '_gf_bs_read_data'
    '_gf_bs_read_int'
    '_gf_bs_read_long_int'
    '_gf_bs_read_u16'
    '_gf_bs_read_u16_le'
    '_gf_bs_read_u32'
    '_gf_bs_read_u32_le'
    '_gf_bs_read_u8'
    '_gf_bs_seek'
    '_gf_bs_skip_bytes'
    '_gf_bs_write_data'
    '_gf_bs_write_int'
    '_gf_bs_write_u16'
    '_gf_bs_write_u8'
    '_gf_codecid_name'
    '_gf_codecid_type'
    '_gf_crc_32'
    '_gf_dynstrcat'
    '_gf_error_to_string'
    '_gf_fclose'
    '_gf_feof'
    '_gf_fflush'
    '_gf_fgetc'
    '_gf_fileio_is_main_thread'
    '_gf_filter_auto_register'
    '_gf_filter_get_dst_name'
    '_gf_filter_get_udta'
    '_gf_filter_pck_discard'
    '_gf_filter_pck_expand'
    '_gf_filter_pck_get_byte_offset'
    '_gf_filter_pck_get_cts'
    '_gf_filter_pck_get_data'
    '_gf_filter_pck_get_dts'
    '_gf_filter_pck_get_duration'
    '_gf_filter_pck_get_property'
    '_gf_filter_pck_get_sap'
    '_gf_filter_pck_get_seek_flag'
    '_gf_filter_pck_get_timescale'
    '_gf_filter_pck_merge_properties'
    '_gf_filter_pck_new_alloc'
    '_gf_filter_pck_new_ref'
    '_gf_filter_pck_ref_props'
    '_gf_filter_pck_send'
    '_gf_filter_pck_set_byte_offset'
    '_gf_filter_pck_set_cts'
    '_gf_filter_pck_set_dependency_flags'
    '_gf_filter_pck_set_dts'
    '_gf_filter_pck_set_duration'
    '_gf_filter_pck_set_framing'
    '_gf_filter_pck_set_interlaced'
    '_gf_filter_pck_set_roll_info'
    '_gf_filter_pck_set_sap'
    '_gf_filter_pck_set_seek_flag'
    '_gf_filter_pck_truncate'
    '_gf_filter_pck_unref'
    '_gf_filter_pid_caps_query'
    '_gf_filter_pid_check_caps'
    '_gf_filter_pid_copy_properties'
    '_gf_filter_pid_drop_packet'
    '_gf_filter_pid_get_info'
    '_gf_filter_pid_get_name'
    '_gf_filter_pid_get_packet'
    '_gf_filter_pid_get_property'
    '_gf_filter_pid_get_property_str'
    '_gf_filter_pid_is_eos'
    '_gf_filter_pid_negotiate_property'
    '_gf_filter_pid_new'
    '_gf_filter_pid_raw_new'
    '_gf_filter_pid_remove'
    '_gf_filter_pid_send_event'
    '_gf_filter_pid_set_discard'
    '_gf_filter_pid_set_eos'
    '_gf_filter_pid_set_framing_mode'
    '_gf_filter_pid_set_name'
    '_gf_filter_pid_set_property'
    '_gf_filter_pid_set_property_dyn'
    '_gf_filter_pid_set_property_str'
    '_gf_filter_pid_would_block'
    '_gf_filter_release_property'
    '_gf_filter_set_name'
    '_gf_fopen'
    '_gf_fopen_ex'
    '_gf_fputc'
    '_gf_fread'
    '_gf_free'
    '_gf_fseek'
    '_gf_fsize'
    '_gf_ftell'
    '_gf_fwrite'
    '_gf_get_bit_size'
    '_gf_itags_find_by_id3tag'
    '_gf_itags_find_by_name'
    '_gf_itags_get_name'
    '_gf_list_add'
    '_gf_list_count'
    '_gf_list_del'
    '_gf_list_del_item'
    '_gf_list_enum'
    '_gf_list_find'
    '_gf_list_get'
    '_gf_list_new'
    '_gf_list_pop_back'
    '_gf_list_rem'
    '_gf_log'
    '_gf_log_get_tool_level'
    '_gf_log_lt'
    '_gf_log_tool_level_on'
    '_gf_malloc'
    '_gf_odf_New_ElemMask'
    '_gf_odf_create_descriptor'
    '_gf_odf_delete_descriptor'
    '_gf_odf_desc_new'
    '_gf_odf_opus_cfg_write_bs'
    '_gf_odf_read_descriptor'
    '_gf_opts_get_bool'
    '_gf_opts_get_int'
    '_gf_opts_get_key'
    '_gf_opts_get_key_count'
    '_gf_pixel_get_size_info'
    '_gf_props_dump_val'
    '_gf_realloc'
    '_gf_strdup'
    '_gf_stream_type_name'
    '_gf_sys_is_test_mode'
    '_gf_sys_old_arch_compat'
    '_gf_timestamp_rescale'
    '_gf_utf8_wcslen'
    '_gf_utf8_wcstombs'
)

SET(PTHREADS
    '_pthread_mutex_init'
    '_pthread_mutex_lock'
    '_pthread_mutex_unlock'
    '_pthread_mutex_destroy'
    '_posix_memalign'
    '_pthread_attr_init'
    '_pthread_attr_setdetachstate'
    '_pthread_cond_destroy'
    '_pthread_cond_init'
    '_pthread_cond_signal'
    '_pthread_cond_wait'
    '_pthread_create'
    '_pthread_join'
    '_sysconf'
)

# zlib symbols (USE_ZLIB=1) needed directly by filters that call zlib
# themselves (e.g. libtiff's deflate/zip support) rather than through gpac.
SET(ZLIB
    '_deflate'
    '_deflateEnd'
    '_deflateInit_'
    '_deflateParams'
    '_deflateReset'
    '_inflate'
    '_inflateEnd'
    '_inflateInit_'
    '_inflateInit2_'
    '_inflateReset'
)

SET(STDLIB
    '___stack_chk_guard'
    '___stack_chk_fail'
    '_vsnprintf'
    '___assert_fail'
    '_lroundf'
    '_mkstemp'
    '_powl'
    '_wmemchr'
    '_sprintf'
    '_siprintf'
    '_sscanf'
    '_snprintf'
    '___small_sprintf'
    '_stdout'
    '_stderr'
    '_stdin'
    '_memmove'
    '_calloc'
    '_realloc'
    '_memcmp'
    '_memchr'
    '_memcpy'
    '_free'
    '_memalign'
    '_getenv'
    '_strcasecmp'
    '_strcmp'
    '_strncasecmp'
    '_strncat'
    '_strncmp'
    '_strcspn'
    '_strcpy'
    '_strstr'
    '_strrchr'
    '_strchr'
    '_strlen'
    '_strtol'
    '_strdup'
    '_strcat'
    '_memset'
    # Needed by ogg_1, libmad_1 and liba52_1 (found by the all-filter scan).
    # libm, so nothing to reconfigure away and nothing worth bundling per
    # filter.
    '_log1p'
    '_exp2'
    '_bsearch'
    '_strtod'
    '_frexp'
    '_exp'
    '_acos'
    '_asin'
    '_atan'
    '_tan'
    '_pow'
    '_qsort'
    '_log'
    '_log2f'
    '_cos'
    '_sin'
    '_ldexp'
    '_round'
    '_roundf'
    '_open'
    '_fcntl'
    '_fstat'
    '_lseek'
    '_read'
    '_write'
    '_close'
    '_lrintf'
    '_lrint'
    '_fwrite'
    '_atoi'
    '_isalnum'
    '_fmemopen'
    '_fread'
    '_fclose'
    '_abort'
    '_exit'
    '_fflush'
    '_fputc'
    '_fiprintf'
    '_fgetc'
    '_fgets'
    '_fopen'
    '_fprintf'
    '_fseek'
    '_fseeko'
    '_getc'
    '_remove'
    '_aligned_alloc'
    '_atof'
    '_htonl'
    '_htons'
    '_isdigit'
    '_isspace'
    '_localtime'
    '_logf'
    '_mktime'
    '_ntohl'
    '_ntohs'
    '_powf'
    '_strncpy'
    '_strtok_r'
    '_uncompress'
    '___wasm_setjmp'
    '___wasm_setjmp_test'
    '_getTempRet0'
    '_setTempRet0'
    '___assert_fail'
    '_atan2'
    '_log2'
    '_time'
    '_vfprintf'
    '___errno_location'
    '_ferror'
    '_fputs'
    '_ftell'
    '_isupper'
    '_log10'
    '_printf'
    '_stat'
    '_tolower'
    '_unlink'
    '__Exit'
    '_sqrt'
    '_sqrtf'
    '_cbrtf'
    '_hypotf'
    '_llroundf'
)

# 128-bit long-double softfloat helpers from libclang_rt.builtins.a, kept
# because __extenddftf2 is imported by libmidi and the other four by libtiff
# (__extendsftf2, __fpclassifyl) and libheif (__fixunstfsi, __floatunsitf).
# They have to be exported rather than pushed into the filters: no build flag
# on those libraries avoids long double, and a per-filter compiler-rt copy
# would cost far more than the ~2KB this adds. __addtf3, __fixtfsi, __multf3
# and __trunctfdf2 used to be listed here and were dropped - no filter paired
# with solver_minimal imports them (see the note at the top of this file).
SET(COMPILER_RT
    '___extenddftf2'
    '___extendsftf2'
    '___fpclassifyl'
    '___fixunstfsi'
    '___floatunsitf'
)

# C++ runtime (new/delete/exception handling) needed by C++ filters such as
# libraw. Symbols internal to a filter's own third-party library (e.g.
# LibRaw's own mangled C++ methods) are NOT listed here - those are
# inter-side-module symbols the filter resolves against its own exports,
# not against the main module (verified by finding such symbols BOTH
# imported and exported by the filter's own .wasm).
SET(CXX_RUNTIME
    '__Znwm'
    '__ZnwmSt11align_val_t'
    '__Znam'
    '__ZdlPv'
    '__ZdlPvSt11align_val_t'
    '__ZdlPvm'
    '__ZdlPvmSt11align_val_t'
    '__ZdaPv'
    '___cxa_atexit'
    '___cxa_begin_catch'
    '___cxa_find_matching_catch_2'
    '___cxa_find_matching_catch_3'
    '___cxa_throw'
    '___resumeException'
# Points d'entree de cxx_stream_anchor.cpp : jamais appeles, listes ici pour que
# l'unite de compilation survive a l'elimination de code mort. Sans eux les
# vtables/typeinfo libc++ qu'elle instancie n'existent pas dans le module
# principal, et le chargement des filtres C++ (libjxl, libheif, libraw) echoue
# sur une entree GOT non resolue (Cannot read properties of undefined 'value').
    '_gpac_cxx_stream_anchor'
    '_gpac_cxx_except_anchor'
    '_gpac_cxx_rtti_anchor'
    '_gpac_cxx_guard_anchor'
    '_gpac_cxx_enumrtti_anchor'
    '_gpac_cxx_sort_anchor'
    '_gpac_cxx_locale_anchor'
# Runtime C++ importe par les filtres image (libjxl, libheif, libraw) :
# instancie par cxx_stream_anchor.cpp ci-dessus, exporte ici.
    '__ZTISt12out_of_range'
    '__ZTVSt12out_of_range'
    '__ZNSt12out_of_rangeD1Ev'
    '___cxa_guard_acquire'
    '___cxa_guard_release'
    '__ZNSt3__26__sortIRNS_6__lessIiiEEPiEEvT0_S5_T_'
    '__ZNSt3__26__sortIRNS_6__lessImmEEPmEEvT0_S5_T_'
    '__ZTVN10__cxxabiv116__enum_type_infoE'
    '__ZNSt3__26localeC1Ev'
    '__ZTVNSt3__215basic_streambufIcNS_11char_traitsIcEEEE'
    '___multi3'
    '_iprintf'
    '_ldexpl'
)

# Symbols the libpoppler filter's poppler-cpp/poppler static libs need
# ("env" imports + GOT.mem imports not already covered above) - found by
# diffing libpoppler_1.wasm's own imports against this file's export
# list, then cross-checked against solver_1's (MAIN_MODULE=1, broad/
# auto-export) symbol table to confirm each one is a real, already-
# working symbol rather than something needing a filter-local shim like
# libjxl's. libc++ string/iostream/locale/mutex/shared_ptr internals,
# and RTTI vtables for the C++ exception hierarchy. FreeType (font
# rendering) is NOT here: gpac_minimal (solver_minimal's own libgpac
# build) never links FreeType at all, so there is nothing to export -
# the filter's CMakeLists.txt instead links a static libfreetype.a
# directly into libpoppler_1.wasm itself (matching how libheif bundles
# its own codec libs, rather than expecting solver_minimal to provide
# them). std::regex and std::filesystem::directory_iterator were
# NOT added here: their symbol footprint (~80 of the mangled libc++
# symbols GOT.mem alone) was disproportionate for two PDFDoc.cc/
# GlobalParams.cc helpers this filter's page-0-to-RGB rendering never
# calls (PDF/A|X|VT|E|UA subtype detection, on-disk poppler-data
# encoding-table discovery this WASM build never bundles anyway) - see
# poppler/PDFDoc.cc's and GlobalParams.cc's own comments at those call
# sites for the source-level fix instead.
SET(POPPLER
    '__ZNKSt3__210filesystem4path10__filenameEv'
    '__ZNKSt3__210filesystem4path16__root_directoryEv'
    '__ZNKSt3__210filesystem4path16lexically_normalEv'
    '__ZNKSt3__210filesystem4path3endEv'
    '__ZNKSt3__210filesystem4path5beginEv'
    '__ZNKSt3__210filesystem4path9__compareENS_17basic_string_viewIcNS_11char_traitsIcEEEE'
    '__ZNKSt3__219__shared_weak_count13__get_deleterERKSt9type_info'
    '__ZNKSt3__26locale9use_facetERNS0_2idE'
    '__ZNKSt3__28ios_base6getlocEv'
    '__ZNSt3__210filesystem4path8iterator11__incrementEv'
    '__ZNSt3__211__call_onceERVmPvPFvS2_E'
    '__ZNSt3__212__next_primeEm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED2Ev'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_externalEPKc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_externalEPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb0EEERS5_PKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb1EEERS5_PKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE21__grow_by_and_replaceEmmmmmmPKc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE25__init_copy_ctor_externalEPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE26__erase_external_with_moveEmm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEmc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertEmPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7replaceEmmPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9push_backEc'
    '__ZNSt3__213__hash_memoryEPKvm'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE3putEc'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE5flushEv'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE6sentryC1ERS3_'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEE6sentryD1Ev'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEED2Ev'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEx'
    '__ZNSt3__213random_deviceC2ERKNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE'
    '__ZNSt3__213random_deviceD1Ev'
    '__ZNSt3__213random_deviceclEv'
    '__ZNSt3__215recursive_mutex4lockEv'
    '__ZNSt3__215recursive_mutex6unlockEv'
    '__ZNSt3__215recursive_mutexC1Ev'
    '__ZNSt3__215recursive_mutexD1Ev'
    '__ZNSt3__219__shared_weak_count14__release_weakEv'
    '__ZNSt3__219__shared_weak_count4lockEv'
    '__ZNSt3__219__shared_weak_countD2Ev'
    '__ZNSt3__24cerrE'
    '__ZNSt3__25ctypeIcE2idE'
    '__ZNSt3__25mutex4lockEv'
    '__ZNSt3__25mutex6unlockEv'
    '__ZNSt3__25mutexD1Ev'
    '__ZNSt3__26__sortIRNS_6__lessIddEEPdEEvT0_S5_T_'
    '__ZNSt3__26chrono12steady_clock3nowEv'
    '__ZNSt3__26localeD1Ev'
    '__ZNSt3__28ios_base4initEPv'
    '__ZNSt3__28ios_base5clearEj'
    '__ZNSt3__29basic_iosIcNS_11char_traitsIcEEED2Ev'
    '__ZNSt3__29to_stringEi'
    '__ZTINSt3__219__shared_weak_countE'
    '__ZTTNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE'
    '__ZTVN10__cxxabiv117__class_type_infoE'
    '__ZTVN10__cxxabiv120__si_class_type_infoE'
    '__ZTVN10__cxxabiv121__vmi_class_type_infoE'
    '__ZTVNSt3__215basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEEE'
    '__ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE'
    '__ZdaPvm'
    '___cxa_pure_virtual'
    '___dynamic_cast'
    '___small_fprintf'
    '_difftime'
    '_fileno'
    '_hypot'
    '_isalpha'
    '_isprint'
    '_isxdigit'
    '_localeconv'
    '_localtime_r'
    '_modf'
    '_pread'
    '_strftime'
    '_timegm'
    '_ungetc'

    # Second batch, found by re-running the scan described above against a
    # rebuilt libpoppler_1.wasm: diff its "env"/GOT imports against
    # solver_minimal_1's exports, drop everything the filter already exports
    # itself (all the FreeType af_*/ft_*/tt_* and libjpeg jpeg_* data
    # symbols are resolved inside the filter, not here), then keep only what
    # solver_1 actually defines. The one that surfaced first at runtime was
    # the basic_ios vtable, since poppler builds a std::ostringstream as soon
    # as it reports anything.
    '__ZNKSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE4findEcm'
    '__ZNKSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7compareEPKc'
    '__ZNKSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7compareEmmPKc'
    '__ZNKSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7compareEmmPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEmc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertEmPKc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6resizeEmc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7replaceEmmPKc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7reserveEm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_mmRKS4_'
    '__ZNSt3__215basic_streambufIcNS_11char_traitsIcEEEC2Ev'
    '__ZNSt3__215basic_streambufIcNS_11char_traitsIcEEED2Ev'
    '__ZNSt3__222__libcpp_verbose_abortEPKcz'
    '__ZNSt3__2plIcNS_11char_traitsIcEENS_9allocatorIcEEEENS_12basic_stringIT_T0_T1_EEPKS6_RKS9_'
    '__ZTVNSt3__214__shared_countE'
    '__ZTVNSt3__219__shared_weak_countE'
    '__ZTVNSt3__28ios_baseE'
    '__ZTVNSt3__29basic_iosIcNS_11char_traitsIcEEEE'
    '_mmap'
    '_munmap'
)

# libheif no longer bundles its own libc++/libc++abi (see the comment in
# filters/libheif/CMakeLists.txt - two C++ runtimes in one process broke
# libc++'s static state across the module boundary), so the runtime now has
# to come from here. Found by the same wasm-dis scan as the POPPLER block
# above, and every one of them cross-checked as actually defined in
# solver_1. Mostly ostream operator<< overloads, the exception hierarchy's
# RTTI/vtables, and the std::thread + condition_variable used by libheif's
# (single-threaded here) worker plumbing.
SET(LIBHEIF
    '__ZNSt11logic_errorC2EPKc'
    '__ZNSt12length_errorD1Ev'
    '__ZNSt20bad_array_new_lengthC1Ev'
    '__ZNSt20bad_array_new_lengthD1Ev'
    '__ZNSt3__212bad_weak_ptrD1Ev'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEb'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEd'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEf'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEi'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEj'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEm'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEs'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEt'
    '__ZNSt3__213basic_ostreamIcNS_11char_traitsIcEEElsEy'
    '__ZNSt3__214basic_iostreamIcNS_11char_traitsIcEEED2Ev'
    '__ZNSt3__218condition_variable10notify_allEv'
    '__ZNSt3__218condition_variable10notify_oneEv'
    '__ZNSt3__218condition_variable4waitERNS_11unique_lockINS_5mutexEEE'
    '__ZNSt3__218condition_variableD1Ev'
    '__ZNSt3__26thread4joinEv'
    '__ZNSt3__26threadD1Ev'
    '__ZNSt9exceptionD2Ev'
    '__ZTINSt3__212bad_weak_ptrE'
    '__ZTISt12length_error'
    '__ZTISt18bad_variant_access'
    '__ZTISt20bad_array_new_length'
    '__ZTTNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE'
    '__ZTVNSt3__212bad_weak_ptrE'
    '__ZTVNSt3__218basic_stringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE'
    '__ZTVSt12length_error'
    '__ZTVSt18bad_variant_access'
    '__ZTVSt9exception'
    '___cxa_allocate_exception'
)

SET(EMSCRIPTEN
    '_emscripten_longjmp'
    '___threwValue'
    '___THREW__'
    '_malloc'
    '_free'
)

SET(SOLVER
    '_get_properties'
    '_set_properties'
    '_destroy'
)

SET(EXTERNAL_FN
    ${GPAC}
    ${FILTERS}
    ${EMSCRIPTEN}
    ${SOLVER}
    ${PTHREADS}
    ${STDLIB}
    ${CXX_RUNTIME}
    ${ZLIB}
    ${COMPILER_RT}
    ${POPPLER}
    ${LIBHEIF}
)

string(JOIN "," EXPORTED_FUNCTIONS ${EXTERNAL_FN})

