
# Symbols solver_minimal_1 exports to the filter side modules it hosts.
#
# Keep this list tight: with MAIN_MODULE=2 an entry does not merely add a
# symbol-table slot, it also pins the function against dead-stripping, so a
# dead export drags its whole call graph into the binary. Trimming 86 unused
# entries once cut ~76KB (-1%) off solver_minimal_1.wasm.
#
# To re-derive the list after adding or rebuilding a filter, disassemble each
# *_1.wasm paired with solver_minimal (wasm-dis), collect its "env"/GOT.mem/
# GOT.func imports, subtract what the filter exports itself, what this binary
# already exports (llvm-nm) and what the JS glue defines (solver_minimal_1.js:
# both the wasmImports object *and* the standalone "function invoke_*"
# trampolines - forgetting the latter inflates the result badly). What is left
# is genuinely missing; cross-check each one against solver_1's symbol table
# before adding it, since GPAC_DISABLE_ISOM and friends mean many gf_isom_*/
# gf_sc_*/gf_scene_* symbols simply do not exist in this build.
#
# Prefer, in order: reconfigure the third-party library so it stops needing
# the symbol (libraw's --disable-openmp, libheif's
# -D__EMSCRIPTEN_STANDALONE_WASM__); else link the dependency into the filter
# (poppler carries its own libjpeg.a); export from here only as a last resort.
# The one exception is the C++ runtime - a filter must NOT bundle its own
# libc++/libc++abi, two copies break libc++'s static state across the module
# boundary (see filters/libheif/CMakeLists.txt).

SET(GPAC
    '_fout_register'
    '_fin_register'
    '_writegen_register'
    '_main'
)

# GPAC core API functions actually imported (from "env") by the filters this
# minimal build is meant to be used with (image/audio decode+transcode via
# writegen - see test-player/*.js's "solver_minimal_1" usages). Generated by
# disassembling each filter's *_1.wasm (wasm-dis) and collecting its "env"
# gf_* imports; symbols only needed by filters that require full gpac (isom/
# scenegraph/compositor, e.g. isobmff, theora, libmpeg2's mp4 muxing path -
# those explicitly use "solver_1", never "solver_minimal_1") are excluded on
# purpose, since gpac_minimal doesn't build ISOBMFF/scenegraph/compositor
# support at all. If a new filter needs to be paired with solver_minimal and
# fails to dlopen with an "undefined symbol" error, re-run the same
# wasm-dis scan against that filter's wasm and add whatever's missing here
# (as long as it's actually defined in libgpac_static.a - GPAC_DISABLE_ISOM
# and friends mean plenty of gf_isom_*/gf_sc_*/gf_scene_*/gf_bifs_* symbols
# simply don't exist in this build).
SET(FILTERS
    '_gf_4cc_to_str'
    '_gf_audio_fmt_bit_depth'
    '_gf_audio_fmt_get_layout_from_cicp'
    '_gf_base64_decode'
    '_gf_bs_align'
    '_gf_bs_available'
    '_gf_bs_bits_available'
    '_gf_bs_del'
    '_gf_bs_enable_emulation_byte_removal'
    '_gf_bs_get_bit_offset'
    '_gf_bs_get_bit_position'
    '_gf_bs_get_content'
    '_gf_bs_get_emulation_byte_removed'
    '_gf_bs_get_position'
    '_gf_bs_get_size'
    '_gf_bs_is_align'
    '_gf_bs_is_overflow'
    '_gf_bs_log_idx'
    '_gf_bs_mark_overflow'
    '_gf_bs_new'
    '_gf_bs_peek_bits'
    '_gf_bs_read_data'
    '_gf_bs_read_int'
    '_gf_bs_read_long_int'
    '_gf_bs_read_u16'
    '_gf_bs_read_u16_le'
    '_gf_bs_read_u32'
    '_gf_bs_read_u32_le'
    '_gf_bs_read_u8'
    '_gf_bs_seek'
    '_gf_bs_skip_bytes'
    '_gf_bs_write_data'
    '_gf_bs_write_int'
    '_gf_bs_write_u16'
    '_gf_bs_write_u8'
    '_gf_codecid_name'
    '_gf_codecid_type'
    '_gf_crc_32'
    '_gf_dynstrcat'
    '_gf_error_to_string'
    '_gf_fclose'
    '_gf_feof'
    '_gf_fflush'
    '_gf_fgetc'
    '_gf_fileio_is_main_thread'
    '_gf_filter_auto_register'
    '_gf_filter_get_dst_name'
    '_gf_filter_get_udta'
    '_gf_filter_pck_discard'
    '_gf_filter_pck_expand'
    '_gf_filter_pck_get_byte_offset'
    '_gf_filter_pck_get_cts'
    '_gf_filter_pck_get_data'
    '_gf_filter_pck_get_dts'
    '_gf_filter_pck_get_duration'
    '_gf_filter_pck_get_property'
    '_gf_filter_pck_get_sap'
    '_gf_filter_pck_get_seek_flag'
    '_gf_filter_pck_get_timescale'
    '_gf_filter_pck_merge_properties'
    '_gf_filter_pck_new_alloc'
    '_gf_filter_pck_new_ref'
    '_gf_filter_pck_ref_props'
    '_gf_filter_pck_send'
    '_gf_filter_pck_set_byte_offset'
    '_gf_filter_pck_set_cts'
    '_gf_filter_pck_set_dependency_flags'
    '_gf_filter_pck_set_dts'
    '_gf_filter_pck_set_duration'
    '_gf_filter_pck_set_framing'
    '_gf_filter_pck_set_interlaced'
    '_gf_filter_pck_set_roll_info'
    '_gf_filter_pck_set_sap'
    '_gf_filter_pck_set_seek_flag'
    '_gf_filter_pck_truncate'
    '_gf_filter_pck_unref'
    '_gf_filter_pid_caps_query'
    '_gf_filter_pid_check_caps'
    '_gf_filter_pid_copy_properties'
    '_gf_filter_pid_drop_packet'
    '_gf_filter_pid_get_info'
    '_gf_filter_pid_get_name'
    '_gf_filter_pid_get_packet'
    '_gf_filter_pid_get_property'
    '_gf_filter_pid_get_property_str'
    '_gf_filter_pid_is_eos'
    '_gf_filter_pid_negotiate_property'
    '_gf_filter_pid_new'
    '_gf_filter_pid_raw_new'
    '_gf_filter_pid_remove'
    '_gf_filter_pid_send_event'
    '_gf_filter_pid_set_discard'
    '_gf_filter_pid_set_eos'
    '_gf_filter_pid_set_framing_mode'
    '_gf_filter_pid_set_name'
    '_gf_filter_pid_set_property'
    '_gf_filter_pid_set_property_dyn'
    '_gf_filter_pid_set_property_str'
    '_gf_filter_pid_would_block'
    '_gf_filter_release_property'
    '_gf_filter_set_name'
    '_gf_fopen'
    '_gf_fopen_ex'
    '_gf_fputc'
    '_gf_fread'
    '_gf_free'
    '_gf_fseek'
    '_gf_fsize'
    '_gf_ftell'
    '_gf_fwrite'
    '_gf_get_bit_size'
    '_gf_itags_find_by_id3tag'
    '_gf_itags_find_by_name'
    '_gf_itags_get_name'
    '_gf_list_add'
    '_gf_list_count'
    '_gf_list_del'
    '_gf_list_del_item'
    '_gf_list_enum'
    '_gf_list_find'
    '_gf_list_get'
    '_gf_list_new'
    '_gf_list_pop_back'
    '_gf_list_rem'
    '_gf_log'
    '_gf_log_get_tool_level'
    '_gf_log_lt'
    '_gf_log_tool_level_on'
    '_gf_malloc'
    '_gf_odf_New_ElemMask'
    '_gf_odf_create_descriptor'
    '_gf_odf_delete_descriptor'
    '_gf_odf_desc_new'
    '_gf_odf_opus_cfg_write_bs'
    '_gf_odf_read_descriptor'
    '_gf_opts_get_bool'
    '_gf_opts_get_int'
    '_gf_opts_get_key'
    '_gf_opts_get_key_count'
    '_gf_pixel_get_size_info'
    '_gf_props_dump_val'
    '_gf_realloc'
    '_gf_strdup'
    '_gf_stream_type_name'
    '_gf_sys_is_test_mode'
    '_gf_sys_old_arch_compat'
    '_gf_timestamp_rescale'
    '_gf_utf8_wcslen'
    '_gf_utf8_wcstombs'
)

SET(PTHREADS
    '_pthread_mutex_init'
    '_pthread_mutex_lock'
    '_pthread_mutex_unlock'
    '_pthread_mutex_destroy'
    '_posix_memalign'
    '_pthread_attr_init'
    '_pthread_attr_setdetachstate'
    '_pthread_cond_destroy'
    '_pthread_cond_init'
    '_pthread_cond_signal'
    '_pthread_cond_wait'
    '_pthread_create'
    '_pthread_join'
    '_sysconf'
)

# zlib symbols (USE_ZLIB=1) needed directly by filters that call zlib
# themselves (e.g. libtiff's deflate/zip support) rather than through gpac.
SET(ZLIB
    '_adler32'
    '_crc32'
    '_deflate'
    '_deflateEnd'
    '_deflateInit_'
    '_deflateInit2_'
    '_deflateParams'
    '_deflateReset'
    '_inflate'
    '_inflateEnd'
    '_inflateInit_'
    '_inflateInit2_'
    '_inflateReset'
    '_inflateReset2'
)

SET(STDLIB
    '___stack_chk_guard'
    '___stack_chk_fail'
    '_vsnprintf'
    '___assert_fail'
    '_lroundf'
    '_mkstemp'
    '_powl'
    '_wmemchr'
    '_sprintf'
    '_siprintf'
    '_sscanf'
    '_snprintf'
    '___small_sprintf'
    '_stdout'
    '_stderr'
    '_stdin'
    '_memmove'
    '_calloc'
    '_realloc'
    '_memcmp'
    '_memchr'
    '_memcpy'
    '_free'
    '_memalign'
    '_getenv'
    '_strcasecmp'
    '_strcmp'
    '_strncasecmp'
    '_strncat'
    '_strncmp'
    '_strcspn'
    '_strcpy'
    '_strstr'
    '_strrchr'
    '_strchr'
    '_strlen'
    '_strtol'
    '_strdup'
    '_strcat'
    '_memset'
    # Needed by ogg_1, libmad_1 and liba52_1 (found by the all-filter scan).
    # libm, so nothing to reconfigure away and nothing worth bundling per
    # filter.
    '_log1p'
    '_exp2'
    '_bsearch'
    '_strtod'
    '_frexp'
    '_exp'
    '_acos'
    '_asin'
    '_atan'
    '_tan'
    '_pow'
    '_qsort'
    '_log'
    '_log2f'
    '_cos'
    '_sin'
    '_ldexp'
    '_round'
    '_roundf'
    '_open'
    '_fcntl'
    '_fstat'
    '_lseek'
    '_read'
    '_write'
    '_close'
    '_lrintf'
    '_lrint'
    '_fwrite'
    '_atoi'
    '_isalnum'
    '_fmemopen'
    '_fread'
    '_fclose'
    '_abort'
    '_exit'
    '_fflush'
    '_fputc'
    '_fiprintf'
    '_fgetc'
    '_fgets'
    '_fopen'
    '_fprintf'
    '_fseek'
    '_fseeko'
    '_getc'
    '_remove'
    '_aligned_alloc'
    '_atof'
    '_htonl'
    '_htons'
    '_isdigit'
    '_isspace'
    '_localtime'
    '_logf'
    '_mktime'
    '_ntohl'
    '_ntohs'
    '_powf'
    '_strncpy'
    '_strtok_r'
    '_uncompress'
    '___wasm_setjmp'
    '___wasm_setjmp_test'
    '_getTempRet0'
    '_setTempRet0'
    '___assert_fail'
    '_atan2'
    '_log2'
    '_time'
    '_vfprintf'
    '___errno_location'
    '_ferror'
    '_fputs'
    '_ftell'
    '_isupper'
    '_log10'
    '_printf'
    '_stat'
    '_tolower'
    '_unlink'
    '__Exit'
    '_sqrt'
    '_sqrtf'
    '_cbrtf'
    '_hypotf'
    '_llroundf'
)

# 128-bit long-double softfloat helpers from libclang_rt.builtins.a, kept
# because __extenddftf2 is imported by libmidi and __extendsftf2 and
# __fpclassifyl by libtiff. They have to be exported rather than pushed into
# the filters: no build flag on those libraries avoids long double, and a
# per-filter compiler-rt copy would cost far more than the ~2KB this adds.
# __fixunstfsi and __floatunsitf were libheif's, which pairs with solver_1
# now; __addtf3, __fixtfsi, __multf3 and __trunctfdf2 were dropped earlier -
# no filter paired with solver_minimal imports them (see the note at the top
# of this file).
SET(COMPILER_RT
    '___extenddftf2'
    '___extendsftf2'
    '___fpclassifyl'
)

# C++ runtime (new/delete/exception handling) needed by C++ filters such as
# libraw. Symbols internal to a filter's own third-party library (e.g.
# LibRaw's own mangled C++ methods) are NOT listed here - those are
# inter-side-module symbols the filter resolves against its own exports,
# not against the main module (verified by finding such symbols BOTH
# imported and exported by the filter's own .wasm).
SET(CXX_RUNTIME
    '__Znwm'
    '__ZnwmSt11align_val_t'
    '__Znam'
    '__ZdlPv'
    '__ZdlPvSt11align_val_t'
    '__ZdlPvm'
    '__ZdlPvmSt11align_val_t'
    '__ZdaPv'
    '___cxa_atexit'
    '___cxa_begin_catch'
    '___cxa_find_matching_catch_2'
    '___cxa_find_matching_catch_3'
    '___cxa_throw'
    '___resumeException'
# Points d'entree de cxx_stream_anchor.cpp : jamais appeles, listes ici pour que
# l'unite de compilation survive a l'elimination de code mort. Sans eux les
# vtables/typeinfo libc++ qu'elle instancie n'existent pas dans le module
# principal, et le chargement des filtres C++ (libjxl, libheif, libraw) echoue
# sur une entree GOT non resolue (Cannot read properties of undefined 'value').
    '_gpac_cxx_stream_anchor'
    '_gpac_cxx_except_anchor'
    '_gpac_cxx_rtti_anchor'
    '_gpac_cxx_guard_anchor'
    '_gpac_cxx_enumrtti_anchor'
    '_gpac_cxx_sort_anchor'
    '_gpac_cxx_locale_anchor'
# Runtime C++ importe par les filtres image (libjxl, libheif, libraw) :
# instancie par cxx_stream_anchor.cpp ci-dessus, exporte ici.
    '__ZTISt12out_of_range'
    '__ZTVSt12out_of_range'
    '__ZNSt12out_of_rangeD1Ev'
    '___cxa_guard_acquire'
    '___cxa_guard_release'
    '__ZNSt3__26__sortIRNS_6__lessIiiEEPiEEvT0_S5_T_'
    '__ZNSt3__26__sortIRNS_6__lessImmEEPmEEvT0_S5_T_'
    '__ZTVN10__cxxabiv116__enum_type_infoE'
    '__ZNSt3__26localeC1Ev'
    '__ZTVNSt3__215basic_streambufIcNS_11char_traitsIcEEEE'
    '___multi3'
    '_iprintf'
    '_ldexpl'
)

# What is left of the former POPPLER and LIBHEIF blocks. Those two filters
# now pair with solver_1 (their tests say so), and the 85 symbols only they
# imported are gone. These 35 stayed because other filters paired with
# solver_minimal import them too - libjxl, libraw, libflif, libape, libpgf,
# libpsd, libilbc, libmpg123 - found by scanning each *_1.wasm's env/GOT
# imports against this list (the scan described at the top of this file).
# Mostly libc++ basic_string internals, the exception hierarchy's RTTI, and
# the __class_type_info vtables every polymorphic C++ type needs.
SET(CXX_RUNTIME_SHARED
    '__ZNKSt3__219__shared_weak_count13__get_deleterERKSt9type_info'
    '__ZNSt11logic_errorC2EPKc'
    '__ZNSt12length_errorD1Ev'
    '__ZNSt20bad_array_new_lengthC1Ev'
    '__ZNSt20bad_array_new_lengthD1Ev'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_externalEPKc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_externalEPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb0EEERS5_PKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE17__assign_no_aliasILb1EEERS5_PKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE25__init_copy_ctor_externalEPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE26__erase_external_with_moveEmm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6appendEPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6insertEmPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7replaceEmmPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE9push_backEc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEmc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6resizeEmc'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE7reserveEm'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEC1ERKS5_mmRKS4_'
    '__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEED1Ev'
    '__ZNSt3__219__shared_weak_count14__release_weakEv'
    '__ZNSt3__219__shared_weak_countD2Ev'
    '__ZTINSt3__219__shared_weak_countE'
    '__ZTISt12length_error'
    '__ZTISt20bad_array_new_length'
    '__ZTVN10__cxxabiv117__class_type_infoE'
    '__ZTVN10__cxxabiv120__si_class_type_infoE'
    '__ZTVSt12length_error'
    '__ZdaPvm'
    '___cxa_allocate_exception'
    '___cxa_pure_virtual'
    '___small_fprintf'
    '_fileno'
)

SET(EMSCRIPTEN
    # Every side module imports env.__stack_pointer (wasm-ld makes the stack
    # pointer an import in any -shared link), and the glue satisfies it from
    # this module's exports via mergeLibSymbols(wasmExports, 'main'). emscripten
    # already asks wasm-ld for the export (REQUIRED_EXPORTS in link.py), but
    # with MAIN_MODULE=2 wasm-metadce then drops it again as unused, since no
    # JS statement receives it - unlike MAIN_MODULE=1, which sets LINKABLE and
    # skips the DCE entirely. Listing it here gives the glue a receiving
    # assignment, which roots it in the DCE graph and keeps the export alive.
    # Without it every filter dies at instantiation with "imported mutable
    # global must be a WebAssembly.Global object".
    '___stack_pointer'
    '_emscripten_longjmp'
    '___threwValue'
    '___THREW__'
    '_malloc'
    '_free'
)

SET(SOLVER
    '_get_properties'
    '_set_properties'
    '_destroy'
)

SET(EXTERNAL_FN
    ${GPAC}
    ${FILTERS}
    ${EMSCRIPTEN}
    ${SOLVER}
    ${PTHREADS}
    ${STDLIB}
    ${CXX_RUNTIME}
    ${ZLIB}
    ${COMPILER_RT}
    ${CXX_RUNTIME_SHARED}
)

string(JOIN "," EXPORTED_FUNCTIONS ${EXTERNAL_FN})

